language: ruby
cache: bundler
before_install:
  - gem install bundler
install:
  - bundle update
script: xvfb-run bundle exec rake
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-head
  - rbx-3
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
